# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('bike_used', models.CharField(max_length=40)),
                ('phone_placement', models.CharField(max_length=40)),
                ('is_public', models.BooleanField()),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydatabase.User')),
            ],
        ),
    ]
