# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0002_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('score', models.IntegerField()),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
                ('altitude', models.BigIntegerField()),
                ('speed', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='userKey',
            new_name='user_fkey',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='trip_fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydatabase.Trip'),
        ),
    ]
