# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
