# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0008_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
