# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0010_auto_20170226_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
