# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydatabase', '0011_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='count',
            new_name='ratings_count',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratings_sum',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
